[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAK_t30NtbOB2WP3vpRInvJf1ACOOFG1ZQ"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "gangi-473df.firebaseapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = """
      default-src 'self' https://*.firebaseio.com https://*.firebase.com https://*.googleapis.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseio.com https://*.firebase.com https://*.googleapis.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https://*.cloudinary.com;
      connect-src 'self' wss://*.firebaseio.com https://*.firebase.com https://*.googleapis.com https://firebase.googleapis.com https://*.cloudfunctions.net https://*.cloudinary.com;
      frame-src 'self' https://*.firebaseapp.com;
      font-src 'self' data:;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin" 