[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAK_t30NtbOB2WP3vpRInvJf1ACOOFG1ZQ"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "gangi-473df.firebaseapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;
      img-src * data: blob: 'unsafe-inline';
      connect-src * 'unsafe-inline';
      frame-src * 'unsafe-inline';
      script-src * 'unsafe-inline' 'unsafe-eval';
      style-src * 'unsafe-inline';
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin" 