[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/static/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.googleapis.com https://*.firebaseapp.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://*.gstatic.com;
      style-src 'self' 'unsafe-inline' https://*.googleapis.com;
      img-src 'self' data: blob: https://*.googleapis.com https://*.gstatic.com https://*.cloudinary.com;
      connect-src 'self' 
        https://*.firebase.com 
        https://*.firebaseio.com 
        https://identitytoolkit.googleapis.com 
        https://*.googleapis.com 
        wss://*.firebaseio.com 
        https://*.cloudinary.com 
        https://firebase.googleapis.com 
        https://firestore.googleapis.com;
      frame-src 'self' https://*.firebaseapp.com https://*.firebase.com;
      font-src 'self' data: https://*.gstatic.com;
      media-src 'self' https: blob:;
      worker-src 'self' blob:;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin" 